CREATE TABLE IF NOT EXISTS SPHERES_OF_COMMUNITY(
    ID INT PRIMARY KEY,
    NAME VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS SKILL(
    ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFESSION(
    ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS HEALTH_STATUS(
    ID INT PRIMARY KEY,
    STATUS VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATION(
    ID INT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS PERSON(
    ID INT PRIMARY KEY,
    NAME VARCHAR(40) NOT NULL,
    LOCATION INT REFERENCES LOCATION(ID),
    STATUS INT REFERENCES SOCIAL_STATUS(ID),
    AGE INT
);

CREATE TABLE IF NOT EXISTS PERSON_LOCATION(
    PERSON INT REFERENCES PERSON(ID),
    LOCATION INT REFERENCES LOCATION(ID),
    HOW_LONG_HAVE_BEEN INTERVAL
);

CREATE TABLE IF NOT EXISTS TASKS(
    ID INT PRIMARY KEY,
    ASSIGNEE INT REFERENCES PERSON(ID),
    DONE_BY INT REFERENCES PERSON(ID),
    DATE DATE,
    DESCRIPTION VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS PERSON_TASK(
    PERSON INT REFERENCES PERSON(ID),
    TASK INT REFERENCES TASKS(ID)
);

CREATE TABLE IF NOT EXISTS PROBLEMS(
    ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROBLEM_PERSON(
    PERSON INT REFERENCES PERSON(ID),
    PROBLEM INT REFERENCES PROBLEMS(ID)
);
