CREATE TABLE IF NOT EXISTS SOCIAL_STATUS(
    ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATION(
    ID INT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS PERSON(
    ID INT PRIMARY KEY,
    NAME VARCHAR(40) NOT NULL,
    LOCATION INT REFERENCES LOCATION(ID),
    STATUS INT REFERENCES SOCIAL_STATUS(ID)
);

CREATE TABLE IF NOT EXISTS TASKS(
    ID INT PRIMARY KEY,
    ASSIGNEE INT REFERENCES PERSON(ID),
    DATE DATE,
    DESCRIPTION VARCHAR(200)
);