/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import server.network.TCPServer;

public class Main {
    public static void main(String[] args) {
        TCPServer server = new TCPServer();
        server.getMessage();
    }
}
